name: Update README with quotes

on:
  push:
      paths:
        - 'QUOTES.txt'  # update when quotes.txt is updated

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read quotes.txt and update README
        run: |
          # read quotes.txt and convert to URI
          QUOTES=$(grep -v '^#' QUOTES.txt | tr '\n' ';' | sed 's/[[:space:]]\+/ /g' | sed 's/;;;[;]*/;;/g' | jq -sRr @uri)

          # replace spaces with + and newlines with ;
          NEW_LINES=$(echo "$QUOTES" | sed 's/ /+/g' | tr '\n' ';')

          # replace lines in README
          if grep -q "lines=" README.md; then
            sed -i "s|lines=.*|lines=${NEW_LINES})|g" README.md
          fi

      - name: Update last updated date in README
        run: |
          TODAY=$(date -u +%Y-%m-%d)
          sed -i -E "s/(Last Updated: )[0-9]{4}-[0-9]{2}-[0-9]{2}/\1$TODAY/" README.md

      - name: Commit and push changes
        run: |
          # check are there any git differences
          if git diff --quiet README.md; then
            echo "No changes to commit."
            exit 0
          fi

          # commit and push
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "🔄 Auto update README last updated date and quotes"
          git push